In [2]:
import numpy as np   

In [3]:
print(np.__version__)


2.3.0


In [4]:
np.array([1,2,3]),type (np.array([1,2,3]))

(array([1, 2, 3]), numpy.ndarray)

In [5]:
np.array([1,2,3,'hello'])

array(['1', '2', '3', 'hello'], dtype='<U21')

In [7]:
array = np.array([1,2,3],dtype=np.int8)
array,array.dtype

(array([1, 2, 3], dtype=int8), dtype('int8'))

In [9]:
2**8-1

255

In [11]:
bin(2**8-1)

'0b11111111'

In [19]:
array = np.array([1,2,3,128,255],dtype=np.uint8)
array

array([  1,   2,   3, 128, 255], dtype=uint8)